name: flutter_mvc
description: A new Flutter project.

publish_to: "none"

#Ios
version: 1.0.4+25

#Android
#version: 1.0.17+18

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.4
  logger: ^2.0.2+1
  flutter_svg: ^2.0.7
  ui_x:
    path: packages/ui_x
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  timezone: ^0.9.0
  flutter_countr:
    path: packages/flutter_countr
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  flutter_image_slideshow: ^0.1.2
  url_launcher: ^6.1.5
  sms_autofill: ^2.2.0
  image_picker: ^1.0.4
  qr_flutter: ^4.0.0
  screenshot: ^2.0.0
  share_plus: ^7.2.1
  file_picker: ^6.0.0
  accordion: ^2.5.1
  jiffy: ^5.0.0
  syncfusion_flutter_charts: ^24.1.43+1
  path_provider: ^2.0.11
  camera: ^0.10.0+3
  pdf:
    path: packages/pdf
  razorpay_flutter: ^1.3.5
  permission_handler: ^11.0.1
  downloads_path_provider_28: ^0.1.2
  flutter_local_notifications: ^16.1.0
  # flutter_html:
  #   path: packages/flutter_html
  #  open_file: ^3.2.1
  #  whatsapp_share2: ^2.0.2
  blur: ^3.1.0
  simple_animations: ^5.0.2
  syncfusion_flutter_pdfviewer: ^24.1.43
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.5.0
  open_file: ^3.3.2
  flutter_widget_from_html: ^0.14.6
  auto_size_text_field: ^2.2.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/newImages/
